name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl --location --request GET 'https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=28Y8q8XFocq8yhKfBzzhUJXjFj2JHCZzIv4P2KIK&sort_hide_null=false&sort_nulls_last=false&data_type=processed&two_year_transaction_period=2020&min_date=01/01/2019&max_date=12/31/2020&contributor_state=OR&sort=-contribution_receipt_date&per_page=100' | jq . > or_contributions.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push